Tslint react
Shopify/tslint-config-shopify pull request #12
Opened 2017-01-30 14:32 UTC by ismail-syed

Integrate [`tslint-react`](https://www.npmjs.com/package/tslint-react). 

5c3df29

2017-01-30 21:52 UTC, lemonmade requested changes

2017-01-30 21:52 UTC, lemonmade commented on README.md
> +## Inline Linting in Text Editors
Is this branch based on your other branch, or vice-versa? Either way, probably want to try to not show the changes in two different PRs.

2017-01-30 21:52 UTC, lemonmade commented on lib/config/rules/react.js
> +  'jsx-ban-props': false,
Seems fine, no props need banning IMO

2017-01-30 21:52 UTC, lemonmade commented on lib/config/rules/react.js
> +  'jsx-curly-spacing': ['always'],
We use `never`

2017-01-30 21:52 UTC, lemonmade commented on lib/config/rules/react.js
> +  'jsx-no-lambda': false,
We should turn this on to match our ESLint config. Do you know if it also warns when using `.bind`?

2017-01-30 21:52 UTC, lemonmade commented on lib/config/rules/react.js
> +  'jsx-no-multiline-js': true,
:-1:, IMO this promotes unreadability in some cases.

2017-01-31 05:18 UTC, GoodForOneFare requested changes
If the "everything inherits from React rules for now" approach gets more linting into Neutron quickly, I'm okay with this solution.

Longer term, we'll definitely need the multi-config approach that my stupidly long comment suggests.

Regardless, PR needs the unrelated changes removed; I can help with that.

2017-01-31 05:18 UTC, GoodForOneFare commented on lib/config/rules/react.js
> +  'jsx-no-lambda': false,
It doesn't :/  There's an [open issue to implement a `jsx-no-bind` rule](https://github.com/palantir/tslint-react/issues/44).

2017-01-31 05:18 UTC, GoodForOneFare commented on index.js
> +  extends: ['tslint-react'],
Extending the `tslint-react` rules here gets *all* projects to inherit React rules.  That's not sustainable because:
- `sewing_kit` users will have the option to set up a non-React project (more rules === slow)
- As we add more config types, a single-inheritance model will pick up conflicting rules (`eslint-plugin-shopify` has 11 configs 😲)

Ideally, what we want is projects to opt into multiple configs like this:

```json
 {
   "extends": [
     "tslint-config-shopify",
     "tslint-config-shopify/react"
  ]
}
```

I did a quick proof-of-concept based on the [shareable configurations doc](https://palantir.github.io/tslint/2016/03/31/sharable-configurations-rules.html), and multiple configs looks doable.

```diff
diff --git a/lib/config/rules/react.js b/lib/config/rules/react.js
new file mode 100644
index 0000000..661522a
--- /dev/null
+++ b/lib/config/rules/react.js
@@ -0,0 +1,27 @@
+// tslint-react
+// Lint rules related to React & JSX for TSLint.
+// Reference https://github.com/palantir/tslint-react
+
+module.exports = {
+  // Enforces a consistent style for multiline JSX elements which promotes ease of
+  // editing via line-wise manipulations as well as maintainabilty via small diffs when changes are made.
+  'jsx-alignment': true,
+  // Allows blacklisting of props in JSX with an optional explanatory message in the reported failure. <FEEDBACK>
+  'jsx-ban-props': false,
+  // Requires or bans spaces between curly brace characters in JSX; Rule options: ["always", "never"]
+  'jsx-curly-spacing': ['always'],
+  // Creating new anonymous functions (with either the function syntax or ES2015 arrow syntax) inside the render call stack works against pure component rendering.
+  // When doing an equality check between two lambdas, React will always consider them unequal values and force the component to re-render more often than necessary. <FEEDBACK>
+  'jsx-no-lambda': false,
+  // Disallows multiline JS expressions inside JSX blocks to promote readability
+  'jsx-no-multiline-js': true,
+  // Passing strings to the ref prop of React elements is considered a legacy feature and will soon be deprecated.
+  // Instead, use a callback.
+  'jsx-no-string-ref': true,
+  // Enforces that JSX elements with no children are self-closing.
+  'jsx-self-close': true,
+  // Enforces that multiline JSX expressions are wrapped with parentheses.
+  // Opening parenthesis must be followed by a newline.
+  // Closing parenthesis must be preceded by a newline.
+  'jsx-wrap-multiline': true,
+};
diff --git a/package.json b/package.json
index dc129f5..4df81b7 100644
--- a/package.json
+++ b/package.json
@@ -32,9 +32,12 @@
   "devDependencies": {
     "eslint": "3.13.x",
     "eslint-plugin-shopify": "^15.1.1",
+    "tslint": "4.3.x",
+    "tslint-react": "2.3.x",
     "typescript": "2.1.x"
   },
   "peerDependencies": {
+    "eslint": "3.13.x",
     "tslint": "4.3.x"
   },
   "dependencies": {
diff --git a/react.js b/react.js
new file mode 100644
index 0000000..9bc6aa1
--- /dev/null
+++ b/react.js
@@ -0,0 +1,4 @@
+module.exports = {
+  rulesDirectory: ['node_modules/tslint-react/rules'],
+  rules: require('./lib/config/rules/react'),
+};
diff --git a/tsconfig.json b/tsconfig.json
deleted file mode 100644
index 1797133..0000000
--- a/tsconfig.json
+++ /dev/null
@@ -1,3 +0,0 @@
-{
-
-}
```

2017-01-31 14:37 UTC, ismail-syed commented on README.md
> +## Inline Linting in Text Editors
Yah, my bad. 
Should've done a PR like this. 

![screen shot 2017-01-31 at 9 36 00 am](https://cloud.githubusercontent.com/assets/6130700/22469084/bcd8a53e-e798-11e6-8e82-2eb61cbf1f6f.png)

2017-01-31 15:10 UTC, ismail-syed commented on index.js
> +  extends: ['tslint-react'],
@GoodForOneFare Thanks for the feedback. I agree, it's better to break up the repo into multiple configs sooner than later. 

I've created an issue for this: #14

2017-01-31 15:24 UTC, ismail-syed commented
@GoodForOneFare @lemonmade:
Fixes are up for this PR. 
Messing up initial [Branch Compare](https://github.com/Shopify/tslint-config-shopify/pull/12/files/0436610c94f91be3ea66a6b7abb2d3ba3c543369#diff-04c6e90faac2675aa89e2176d2eec7d8) on PRs #11 #12 #13 lead to some of this PR ugliness. My apologies.

2017-01-31 18:25 UTC, GoodForOneFare commented on circle.yml
> +  pre:
Please use the simplified yarn setup that's now available: https://circleci.com/docs/yarn/#full-example

2017-01-31 18:26 UTC, GoodForOneFare commented on package.json
> +  "version": "0.0.0-semantically-released",
As discussed in Slack, `semantic-release` is a bigger discussion than this PR, so it should be removed for now.

2017-01-31 20:20 UTC, GoodForOneFare commented on lib/config/rules/react.js
> +  'jsx-wrap-multiline': true,
@lemonmade pointed out that this promotes unreadability in some cases.  Should be `false`.

2017-01-31 20:40 UTC, ismail-syed commented on lib/config/rules/react.js
> +  'jsx-wrap-multiline': true,
Fixed! 👍

2017-01-31 20:44 UTC, GoodForOneFare approved these changes

2017-01-31 20:50 UTC, merged