Split into configs
Shopify/tslint-config-shopify pull request #29
Opened 2017-02-21 12:39 UTC by ismail-syed

Add `tslint-config-shopify/base` and `tslint-config-shopify/typed` configs as per [tslint's sharable configurations docs](https://palantir.github.io/tslint/2016/03/31/sharable-configurations-rules.html)

https://github.com/Shopify/tslint-config-shopify/issues/14

2017-02-21 20:44 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base"
Thinking about it some more, it makes sense to make people explicitly opt out of typed rules.  i.e.,:
1. The default `tslint-config-shopify` export is a very opinionated set of Shopify's rules (typed included)
2. There's a separate `tslint-config-shopify/react` export (à la https://github.com/Shopify/eslint-plugin-shopify/blob/master/index.js#L16)
3. ... the react config extends the base config (à la https://github.com/Shopify/eslint-plugin-shopify/blob/master/lib/config/react.js#L4)
4. Then we have a separate `tslint-config-shopify/untyped` config that extends the base config, but disables all typed rules

Then a consuming project can have:
- A `tslint-full.json` that extends `tslint-config-shopify` (or `tslint-config-shopify/react`), 
- A `tslint.json` that does:
```json
{
  "extends": [
    "./config/tslint/full.json",
    "tslint-config-shopify/untyped"
  ]
}
```

2017-02-21 21:08 UTC, ismail-syed commented on README.md
> +  "extends": "tslint-config-shopify/base"
Okay , essentially 4 configs
* base
* react
* typed
* untyped

2017-02-22 03:30 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base"
The base rules will include all typed rules, so just 3 configs.  With the assumption that I'm predicting `extends`' behaviour correctly.

2017-02-22 03:32 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base"
Here's a list of all typed rules:

```js
{
  // Warns for an awaited value that is not a Promise.
  "await-promise": false,
  // Enforces documentation for important items be filled out.
  "completed-docs": false,
  // Warns on comparison to a boolean literal, as in x === true.
  "no-boolean-literal-compare": false,
  // Promises returned by functions must be handled appropriately.
  "no-floating-promises": false,
  // Disallows iterating over an array with a for-in loop.
  "no-for-in-array": false,
  // Disallow type inference of {} (empty object type) at function and constructor call sites
  "no-inferred-empty-object-type": false,
  // Warns when a method is used as outside of a method call.
  "no-unbound-method": false,
  // Requires any function or method that returns a promise to be marked async.
  "promise-function-async": false,
  // When adding two variables, operands must both be of type number or of type string.
  "restrict-plus-operands": false,
  // Usage of &amp;&amp; or || operators should be with boolean operands and
  // expressions in If, Do, While and For statements should be of type boolean
  "strict-boolean-expressions": false,
  // Warns for type predicates that are always true or always false. Works for ‘typeof’ comparisons to constants (e.g. ‘typeof foo === “string”’), and equality comparison to ‘null’/’undefined’. (TypeScript won’t let you compare ‘1 === 2’, but it has an exception for ‘1 === undefined’.) Does not yet work for ‘instanceof’. Does not warn for ‘if (x.y)’ where ‘x.y’ is always truthy. For that, see strict-boolean-expressions.
  "strict-type-predicates": false,
}
```

2017-02-22 03:48 UTC, ismail-syed commented on README.md
> +  "extends": "tslint-config-shopify/base"
Awesome, thanks for that list of rules 👍. 
Did you narrow down that list manually?

2017-02-22 04:49 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base"
I found the rules by searching the tslint repo for `requiresTypeInfo: true`.

2017-02-22 04:58 UTC, ismail-syed commented on README.md
> +  "extends": "tslint-config-shopify/base"
Added/cleaned up the configs in 2f3b368.

2017-02-22 17:58 UTC, GoodForOneFare requested changes
Update the `untyped` rules, and fix the docs and this'll be good to go.

2017-02-22 17:58 UTC, GoodForOneFare commented on lib/config/untyped.js
> +    'completed-docs': false,
This isn't a typed rule.  My original version of the list wasn't accurate, and you must've grabbed it faster than I could update :P  Please checkout the comment and update this.

2017-02-22 17:58 UTC, GoodForOneFare commented on lib/config/react.js
> +  'extends': ['./base', 'tslint-react'],
This seems weird.  The react config is extending itself?  Any reason to not just extend `./base`?

2017-02-22 17:58 UTC, GoodForOneFare commented on CHANGELOG.md
> +## [1.1.5] - 2017-02-21
Date needs to be bumped 😛

2017-02-22 17:58 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base"
People can just use `"extends": "tslint-config-shopify"` (because `package.json`'s `main` points there.

2017-02-22 17:58 UTC, GoodForOneFare commented on README.md
> +  "extends": "tslint-config-shopify/base",
Again, no need for `base`.

2017-02-22 18:28 UTC, ismail-syed commented on lib/config/react.js
> +  'extends': ['./base', 'tslint-react'],
This is how it's specified in their [usage documentation](https://github.com/palantir/tslint-react#usage)
I presume it helps tslint know that we want to use tslint-react and then we override the preconfigured tslint-react rules.

2017-02-22 20:41 UTC, GoodForOneFare requested changes

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +  "extends": ["tslint-config-shopify/typed"]
s/`typed`/`untyped`.

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +To resolve this issue, you can extend the typed configuration
s/`typed`/`untyped`

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +However, this will omit enforcing rules that require type-checking.
s/`this will omit enforcing`/`this will not enforce`.

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +Eg: `./config/tslint-base.json`
To be consistent with the neutron setup, use `tslint-full.json`.

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +Then update your CLI tslint script to run against `tslint-base.json`.
`tslint-full.json`

2017-02-22 20:41 UTC, GoodForOneFare commented on README.md
> +    "tslint": "tslint -c ./config/tslint-base.json './src/**/*.{ts,tsx}' --project tsconfig.json --type-check"
`tslint-full.json`

2017-02-22 21:04 UTC, ismail-syed commented
@GoodForOneFare README fixes are up in 9d87ded

2017-02-22 21:24 UTC, GoodForOneFare approved these changes
Good stuff 👍

2017-02-22 21:31 UTC, merged