[WIP] Update TSLint to latest v5.1.0
Shopify/tslint-config-shopify pull request #61
Opened 2017-05-02 01:45 UTC by ismail-syed

2017-05-02 15:03 UTC, lemonmade requested changes

2017-05-02 15:03 UTC, lemonmade commented on CHANGELOG.md
> +- Added new `tslint` [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500), [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) rules and new `tslint-react
Weird sentence, and missing a space after `tslint-react` I think

2017-05-02 15:03 UTC, lemonmade commented on src/rules/maintainability.ts
> +  'no-unnecessary-callback-wrapper': false,
Why `false`?

2017-05-02 15:03 UTC, lemonmade commented on src/rules/react.ts
> +  'jsx-no-bind': false,
Why `false` here?

2017-05-02 15:03 UTC, lemonmade commented on src/rules/style.ts
> +  // Don’t if you import “foo” anyway.
this sentence doesn't seem to make sense? As a result I don't understand the rule

2017-05-02 15:12 UTC, ismail-syed commented on src/rules/style.ts
> +  // Don’t if you import “foo” anyway.
No idea either  😐 
https://palantir.github.io/tslint/rules/no-reference-import/

2017-05-02 15:15 UTC, ismail-syed commented on src/rules/maintainability.ts
> +  'no-unnecessary-callback-wrapper': false,
Left this up for discussion, I'll turn this on.

2017-05-02 15:15 UTC, ismail-syed commented on src/rules/react.ts
> +  'jsx-no-bind': false,
Same here, I'll turn it on.

2017-05-02 15:18 UTC, lemonmade commented on src/rules/style.ts
> +  // Don’t if you import “foo” anyway.
lol wtf. My guess would be that it means to not use a `/// reference` comment for things that are already imported. I would just turn it on for now and we can disable if it is doing something unexpected.

2017-05-02 15:25 UTC, ismail-syed commented on src/rules/maintainability.ts
> +  'no-unnecessary-callback-wrapper': false,
Fixed: 03f5c03

2017-05-02 15:25 UTC, ismail-syed commented on src/rules/react.ts
> +  'jsx-no-bind': false,
Fixed 03f5c03

2017-05-02 15:25 UTC, ismail-syed commented on CHANGELOG.md
> +- Added new `tslint` [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500), [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) rules and new `tslint-react
Fixed: 951c656

2017-05-02 15:27 UTC, ismail-syed commented on src/rules/style.ts
> +  // Don’t if you import “foo” anyway.
Yup, that what it seems to be doing. 
https://github.com/palantir/tslint/blob/master/test/rules/no-reference-import/test.d.ts.lint

2017-05-02 15:29 UTC, ismail-syed commented on src/rules/style.ts
> +  // Don’t if you import “foo” anyway.
Fixed: da1c74e

2017-05-02 15:29 UTC, ismail-syed commented
@lemonmade Fixes are up 👍

2017-05-02 15:56 UTC, GoodForOneFare requested changes

2017-05-02 15:56 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
> +class TrailingCommaInterfaceWalker extends Lint.RuleWalker {
Convention in `tslint` is to put the walker after the rule (e.g., [unified-signatures-rule](https://github.com/palantir/tslint/blob/b4be183b8e3d9fa2e07d7e0ab34c500ee0b0bb7b/src/rules/unifiedSignaturesRule.ts#L59)).

2017-05-02 15:56 UTC, GoodForOneFare commented on CHANGELOG.md
> +- Added new `tslint` rules from [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500) and [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) releases
Just reading this, I'd assume that all of these new rules are enabled.

2017-05-02 15:56 UTC, GoodForOneFare commented on CHANGELOG.md
> +
Should mention `no-unused-new`'s removal

2017-05-02 15:56 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'no-sparse-arrays': false,
No sparse arrays in Neutron.  What's the value of allowing them?

2017-05-03 17:04 UTC, ismail-syed commented on src/customRules/trailingCommaInterfaceRule.ts
> +class TrailingCommaInterfaceWalker extends Lint.RuleWalker {
For some reason, after updating I kept getting 
```
ERROR: src/customRules/trailingCommaInterfaceRule.ts[20, 41]: variable 'TrailingCommaInterfaceWalker' used before declaration
```

2017-05-03 17:10 UTC, ismail-syed commented on src/rules/functionality.ts
> +  'no-sparse-arrays': false,
The rationale behind it is `Missing elements are probably an accidentally duplicated comma.`

2017-05-03 17:10 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
> +class TrailingCommaInterfaceWalker extends Lint.RuleWalker {
Ah, okay.  They must use looser rules than us.

2017-05-03 17:14 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'no-sparse-arrays': false,
I understand the rule.  I'm asking why it's not being enforced.

2017-05-03 17:15 UTC, ismail-syed commented on CHANGELOG.md
> +- Added new `tslint` rules from [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500) and [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) releases
Would it be worth the effort to manually have them listed here as well?

2017-05-03 17:19 UTC, ismail-syed commented on CHANGELOG.md
> +
Fixed 006583d

2017-05-03 17:24 UTC, GoodForOneFare commented on CHANGELOG.md
> +- Added new `tslint` rules from [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500) and [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) releases
I don't understand your question.  To be clear, I'm saying:
> This list makes it look like we've enabled 7 new rules, but we've really enabled 5

i.e., should the list provide more context like:

```
* `no-invalid-template-strings`
* `no-sparse-array` (disabled)
```

... or are we happy with consumers digging in to see what is/isn't enforced by default?

2017-05-03 17:45 UTC, ismail-syed commented on CHANGELOG.md
> +- Added new `tslint` rules from [v5.0.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v500) and [v5.1.0](https://github.com/palantir/tslint/blob/master/CHANGELOG.md#v510) releases
Ahhhh, I assumed you'd like to have each rules value listed. 

I like the `(disabled)` suggestion. 👍

2017-05-03 17:46 UTC, ismail-syed commented on src/rules/functionality.ts
> +  'no-sparse-arrays': false,
Enabled 3dbe709

2017-05-03 17:58 UTC, GoodForOneFare commented on CHANGELOG.md
> +    * `jsx-no-bind` (tslint-react)
What does the `(tslint-react)` mean here?  That's already covered by the parent bullet point.

2017-05-03 18:04 UTC, ismail-syed commented on CHANGELOG.md
> +    * `jsx-no-bind` (tslint-react)
Oh yes, forgot to remove it after refactoring this section.

2017-05-03 18:05 UTC, ismail-syed commented on CHANGELOG.md
> +    * `jsx-no-bind` (tslint-react)
Fixed ce85081

2017-05-03 18:06 UTC, GoodForOneFare approved these changes
I was so happy when this PR just appeared out of thin air 👍 Thank you for acting like an owner!

2017-05-03 18:09 UTC, ismail-syed commented
😄  ❤️

2017-05-03 18:13 UTC, merged