Add fixer for trailing-comma-interface rule
Shopify/tslint-config-shopify pull request #62
Opened 2017-06-04 05:07 UTC by ismail-syed

This fixer will help with integrating prettier into our formatting/linting, if we decide to go with it. 

Related to https://github.com/Shopify/tslint-config-shopify/issues/51

2017-06-04 16:07 UTC, GoodForOneFare requested changes
You can add `test/rules/trailing-comma-interface/test.ts.fix`, and tslint will magically verify that your fix works ([Example fix file from the main repo]( https://github.com/palantir/tslint/blob/master/test/rules/align/members/test.ts.fix)).

Please remove the trailing comma from `moe: number,`.  This'll verify that trailing commas are enforced for last lines.

2017-06-06 01:28 UTC, ismail-syed commented
@GoodForOneFare This is good for another quick 👀

2017-06-06 01:41 UTC, GoodForOneFare commented on test/rules/trailing-comma-interface/test.ts.lint
> -  moe: number,
Why is `moe` deleted?  I asked for the comma to be removed from the end of its line.  This will verify that omitted commas are added by the fixer.

2017-06-06 02:33 UTC, ismail-syed commented
Ek, my apologies. I need to read better :/

I'll get that fixed soon. At the gym 10x'ing my fitness atm. Haha, lol.

2017-06-06 04:12 UTC, ismail-syed commented
Added back the test case without the comma. Updated the rule as well because 
```
moe: number
```
would get fixed to 
```
moe: numbe,
```

Good catch Gord, thanks! 😄

2017-06-06 05:29 UTC, GoodForOneFare requested changes

2017-06-06 05:29 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
>      node.members.map((propertySignature) => {
Nothing's consuming the result of the loop.  `map` => `forEach`.

2017-06-06 05:29 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
> +        if (lastChar !== ',') {
Try to make your callbacks do one thing well.  Conditions are cognitive load.

Chain a couple of callbacks instead:
```
    node.members
      .filter((propertySignature) => propertySignature.getText().slice(-1) !== ',')
      .forEach((propertySignature) => {
        const lastChar = propertySignature.getText().slice(-1);
```

2017-06-06 05:29 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
> +    const potentialDelimiters = [';'];
What's up with the indentation in this file?  I see 2, 3, and 4 char indents.

2017-06-06 05:29 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
> +          const replacementText = (potentialDelimiters.indexOf(lastChar) === -1) ? `${lastChar},` : ',';
`potentialDelimiters` feels like an over-abstraction; it'd take a language change to add anything to this array!

Use `arr.includes(foo)` if you're not going to use the index.

Favour truthy comparisons.  Most conditions are truth-first, so it's easy to miss inversions.  eslint has a [no-negated-condition](http://eslint.org/docs/rules/no-negated-condition) rule to enforce this (I wonder if they gave it an intentionally bad name?)

So, something like:
```
const replacementText = (lastChar === ';' ? ',' : `${lastChar},`;
```

2017-06-06 15:08 UTC, ismail-syed commented on src/customRules/trailingCommaInterfaceRule.ts
> +    const potentialDelimiters = [';'];
Had something wonky going on in VSCode.

2017-06-06 15:08 UTC, ismail-syed commented on src/customRules/trailingCommaInterfaceRule.ts
> +        if (lastChar !== ',') {
😍

2017-06-06 15:10 UTC, GoodForOneFare approved these changes
👍

2017-06-06 15:11 UTC, merged