Bump up tslint v5.4.3 and add new rules
Shopify/tslint-config-shopify pull request #68
Opened 2017-06-06 20:01 UTC by ismail-syed

Bumped up tslint to the lastest. Some nice goodies came out in the last few minor bumps.

2017-06-06 20:02 UTC, ismail-syed commented on src/customRules/importTypeOrderRule.ts
> -const importStuctureOrder = [ImportType.External, ImportType.Absolute, ImportType.Ancestor, ImportType.Sibling];
Was flagged by `no-unused-variable` 👍

2017-06-06 20:11 UTC, ismail-syed commented on src/customRules/trailingCommaInterfaceRule.ts
>          const lastCharPosition = propertySignature.getStart() + propertySignature.getWidth() - 1;
This was getting flagged after updating. I think it might be related to https://github.com/palantir/tslint/issues/2571

2017-06-07 04:34 UTC, GoodForOneFare requested changes
Nice work.

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'no-unused-variable': true,
Applying this PR in neutron, I get this output:

```
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
... SNIP ...
```

Just disable this.

2017-06-07 04:34 UTC, GoodForOneFare commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
`no-boolean-literal-compare` requires type info, so it should be in here.

`no-use-before-declare`, too.

2017-06-07 04:34 UTC, GoodForOneFare commented on src/untyped.ts
> +    'deprecation': true,
The point of this file is to disable all type-checking rules.  Otherwise VS Code pops up warnings about not having access to typechecking info.

2017-06-07 04:34 UTC, GoodForOneFare commented on src/customRules/trailingCommaInterfaceRule.ts
>          const lastCharPosition = propertySignature.getStart() + propertySignature.getWidth() - 1;
From that issue:
> If I remove the "no-unused-variable" rule, the "restrict-plus-operands" rule is not complaining anymore.

Another of my comments suggests disabling `no-unused-variable`.  Please verify that this disable is still necessary after disabling `no-unused-variable`.

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'no-object-literal-type-assertion': false,
> Rationale
> 
> Always prefer const x: T = { ... }; to const x = { ... } as T;. The type assertion in the latter case is either unnecessary or hides an error. The compiler will warn for excess properties with this syntax, but not missing required fields. For example: const x: { foo: number } = {} will fail to compile, but const x = {} as { foo: number } will succeed.

Makes sense to me.

Affected files in `neutron`:
```
app/sections/PatternLibrary/components/ModalTestCard.tsx[54, 19]
app/sections/PatternLibrary/components/ModalTestCard.tsx[62, 21]
app/sections/PatternLibrary/components/ModalTestCard.tsx[68, 19]
app/store/reducers/forms/actionCreators.ts[59, 38]
app/store/reducers/forms/formReducer.ts[51, 23]
app/store/reducers/forms/formReducer.ts[79, 23]
client/embedded/App.tsx[194, 42]
packages/@shopify/reportify-container/src/decorator.tsx[234, 6]
packages/@shopify/reportify-container/src/query.ts[124, 6]
```

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'prefer-conditional-expression': false,
Ehhhhhhh.  I say leave it off.  It'll cause unnecessary flipping between if/ternary expressions.  Harder `git blame`.

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/prefer-conditional-expression/test.ts.lint)

It looks like [only a single file in neutron is affected](server/middleware/error-response.ts).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'prefer-object-spread': true,
👍

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/functionality.ts
> +  'use-default-type-parameter': false,
[Examples](https://github.com/palantir/tslint/blob/master/test/rules/use-default-type-parameter/test.ts.lint).

Doesn't flag any neutron errors.  I guess there's no harm in turning it on?

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/maintainability.ts
> +  'deprecation': true,
👍

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/maintainability.ts
> +  'number-literal-format': true,
👍

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/typescript.ts
> +  'no-unnecessary-type-assertion': true,
👍 

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/no-unnecessary-type-assertion/test.ts.lint).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'type-literal-delimiter': false,
👍 to `false`.  Pretty sure that we favour interfaces over types-with-members, so this rule won't do much for us.

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/type-literal-delimiter/test.ts.lint).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'switch-final-break': true,
👍 

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/switch-final-break/default/test.ts.lint).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'prefer-switch': false,
👍 to `false`.

This is bad guidance.  Convert that 💩 into a well-named `const`.

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/prefer-switch/default/test.ts.lint).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'no-irregular-whitespace': true,
👍  (even though I secretly love column alignment in personal projects 😛)

[Examples](https://github.com/palantir/tslint/blob/master/test/rules/no-irregular-whitespace/test.ts.lint).

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'no-boolean-literal-compare': true,
👍

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'encoding': true,
👍

2017-06-07 04:34 UTC, GoodForOneFare commented on src/rules/style.ts
> +  'binary-expression-operand-order': true,
👍 

I guess this is equivalent to [eslint's yoda](http://eslint.org/docs/rules/yoda)?  So having this on is in line with our eslint rules.

2017-06-07 13:19 UTC, lemonmade commented on src/rules/functionality.ts
> +  'no-object-literal-type-assertion': false,
Seems like a good rule to me 👍

2017-06-07 13:19 UTC, lemonmade commented on src/rules/functionality.ts
> +  'no-unused-variable': true,
Agreed, we should continue to use TS's version of this.

2017-06-07 13:19 UTC, lemonmade commented on src/rules/functionality.ts
> +  'prefer-conditional-expression': false,
👍

2017-06-07 13:19 UTC, lemonmade commented on src/rules/functionality.ts
> +  'use-default-type-parameter': false,
I'd leave it off, I don't see why specifying it as the default should really matter (and will likely make it more clear at the call site)

2017-06-07 13:19 UTC, lemonmade commented on src/rules/style.ts
> +  'type-literal-delimiter': false,
We prefer comma here — can we specify that instead of semis?

2017-06-07 15:28 UTC, ismail-syed commented on src/untyped.ts
> +    'deprecation': true,
Ops, nice catch.

2017-06-07 23:32 UTC, ismail-syed commented on src/rules/style.ts
> +  'type-literal-delimiter': false,
We have our own custom rule for this, [trailing-comma-interface](https://github.com/Shopify/tslint-config-shopify/blob/master/src/customRules/trailingCommaInterfaceRule.ts), so we have this covered.

2017-06-07 23:41 UTC, ismail-syed commented on src/rules/functionality.ts
> +  'no-object-literal-type-assertion': false,
Enabled: https://github.com/Shopify/tslint-config-shopify/pull/68/commits/86122d599e65c9a58bf9c9d448b8b8a049995c95

2017-06-07 23:42 UTC, ismail-syed commented on src/rules/functionality.ts
> +  'no-unused-variable': true,
Enabled https://github.com/Shopify/tslint-config-shopify/pull/68/commits/f7258d9f96b5e1ee22a4706158242bc6ba3a48d0

2017-06-07 23:43 UTC, ismail-syed commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
👍

2017-06-07 23:45 UTC, ismail-syed commented on src/rules/style.ts
> +  'binary-expression-operand-order': true,
Seems like it. Lol, didn't know there was a eslint rule named `yoda`

2017-06-07 23:46 UTC, ismail-syed commented on src/customRules/trailingCommaInterfaceRule.ts
>          const lastCharPosition = propertySignature.getStart() + propertySignature.getWidth() - 1;
Disabling `no-unused-variable` fixes the issue. Yay 😄

2017-06-07 23:48 UTC, ismail-syed commented
Comments addressed. We're ready for another 👀

2017-06-08 02:30 UTC, GoodForOneFare commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
This file should contain these lines:
```
    "no-boolean-literal-compare": false,
```

```
    "no-use-before-declare": false,
```

2017-06-08 02:31 UTC, GoodForOneFare commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
It'd be useful for the missing rules script to flag rules that require type info (not v1, of course).

2017-06-08 02:34 UTC, GoodForOneFare approved these changes
Add the two `untyped.ts` rules and this is GTG.

No need to tag me for further review.

2017-06-08 14:00 UTC, ismail-syed commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
[`no-use-before-declare`](https://github.com/Shopify/tslint-config-shopify/pull/68/files#diff-b680e6509a051d5276efb842d9885773R30) and [`no-boolean-literal-compare`](https://github.com/Shopify/tslint-config-shopify/pull/68/files#diff-b680e6509a051d5276efb842d9885773R12) are already in the `untyped.ts` file?

2017-06-08 14:11 UTC, GoodForOneFare commented on src/untyped.ts
> +    // Warns if a type assertion does not change the type of an expression.
Then Github's diff isn't displaying properly for me.  Just merge the damn thing.

2017-06-08 14:25 UTC, merged