Update rules: match-default-export-name & indent
Shopify/tslint-config-shopify pull request #69
Opened 2017-06-06 20:44 UTC by ismail-syed

2017-06-06 20:51 UTC, ismail-syed commented on src/rules/style.ts
> +  'match-default-export-name': false,
We had this enabled to generate some feedback. It creates more noise than benefits.

2017-06-07 02:00 UTC, GoodForOneFare requested changes

2017-06-07 02:00 UTC, GoodForOneFare commented on CHANGELOG.md
> +* Set indentation size in `indent` rule [(#69)](https://github.com/Shopify/tslint-config-shopify/pull/69)
Newline between this and the next header.

2017-06-07 04:33 UTC, ismail-syed commented on CHANGELOG.md
> +* Set indentation size in `indent` rule [(#69)](https://github.com/Shopify/tslint-config-shopify/pull/69)
👍

2017-06-07 05:06 UTC, GoodForOneFare approved these changes

2017-06-07 23:27 UTC, merged