Move from untyped->typed config
Shopify/tslint-config-shopify pull request #71
Opened 2017-06-25 14:01 UTC by lemonmade

I'm working through adding a linting command for Sewing Kit, and it's much easier if the "base" config of the project has no type-checking commands; it lets us automatically create a "typed" version for CI (this doesn't work well right now because the editor config needs to extend the "full" config, then disable type checking, which means the "full" config always needs to exist).

2017-06-25 15:10 UTC, GoodForOneFare commented
Is the suggestion that:
1. There will be less friction when bootstrapping a project because only one config is necessary
2. CI will automatically do a fully-typed lint, even if the user has not defined a script to run tslint with `--type-check`

?

2017-06-25 18:40 UTC, lemonmade commented
The way I have this working is that, when you run the sewing-kit lint command, it creates a private config file that extends the project's config (which now just includes the default/ React configs) and uses the correct CLI arguments to get type checking. This means only one config file for the project, which makes things a lot simpler

2017-06-26 13:43 UTC, ismail-syed commented
I think we'll need to change [`./build/untyped`](https://github.com/Shopify/tslint-config-shopify/blob/typed-config/tslint.json#L3) to `./build/typed` in this project's `tslint.json`

2017-06-26 14:53 UTC, ismail-syed requested changes
Giving this a 🎩 through Neutron atm.

I like this approach better, it simplifies the onboarding process for consumers. 

However, previously every rule in the `untyped` config would be turned off, and whether we like that rule to be `on/off` is based on it's setting in `typescript.ts`, `functionality.ts` etc.  

We have a bit off the opposite now. I propose that we keep only one setting for the type-checking rules (which will live in our `typed.ts` config) and remove all the one we have turned off in `typescript.ts`, `functionality.ts` etc.

2017-06-26 14:53 UTC, ismail-syed commented on README.md
> +    "tslint": "tslint --config ./config/tslint/full.json './src/**/*.{ts,tsx}' --project tsconfig.json --type-check"
From the [`v5.4.0`](https://github.com/palantir/tslint/releases/tag/5.4.0) release: 

>The --type-check CLI option now only enables checking for compiler errors before linting. It is no longer required to enable rules that use the type checker -- only need to supply --project now.

Forgot to update the docs when I last updated last time. 😞 
If you could remove the `--type-check` in here, that would be 👍

2017-06-26 14:56 UTC, ismail-syed commented on README.md
> +    "tslint": "tslint --config ./config/tslint/full.json './src/**/*.{ts,tsx}' --project tsconfig.json --type-check"
I also noticed a 1s increase in performance within this repo when we ran `tslint`. If we update subsequent repo's we should remove `--type-check`, I think we'll see some a small performance boost.

2017-06-26 16:08 UTC, ismail-syed commented
Finished 🎩 with Neutron. No issues 👍

2017-06-26 19:25 UTC, ismail-syed approved these changes
💯 

🚢

2017-06-26 19:25 UTC, GoodForOneFare commented
Please don't ship yet.

2017-06-26 19:26 UTC, ismail-syed commented
Gord says 🛑 
🙅‍♂️

2017-06-26 20:15 UTC, GoodForOneFare reviewed
What's the benefit of the untyped + full config nowadays?

In the past, the typed config made VS Code unusable.  Now, a few `foo-bar-rule requires type checking` terminal messages appear on startup, but the plugin still functions beautifully.

Atom's tslint plugin works without any problems, too.

I think this PR should either:
1. Do away with the two-config concept entirely

2. If we're still worried about the `requires type checking` warnings, we shouldn't ship this because those messages are easily introduced by project-specific rule overrides

2017-06-26 20:27 UTC, ismail-syed commented
Thanks for remembering to 🎩  with Atom!
❤️ 

Atom's error messages a super obnoxious so it's easy to see if things break.

2017-06-26 20:42 UTC, ismail-syed commented
The config that editors pick up shouldn't have any type checking rules enabled, we shouldn't be seeing this. 🤔 

Let's sit down together tomorrow and see where this 💩 the bed.

2017-06-26 20:55 UTC, GoodForOneFare commented
There's no 💩, AFAIC.  I'm okay with VS Code displaying some warnings buried in a console.

I think the config split is an artifact of when the lint plugins gave ridiculous feedback on typed rules (popped up a warning dialog on every save, IIRC?)

-----

You can easily get type warnings by adding an override.  e.g.,

Create `custom-rules.js`:
```
module.exports = {
  rules: {
    "await-promise": true,
  },
};
```

Then adding them after the base rules:
```
{
  "extends": [
    "tslint-config-shopify",
    "./custom-rules.js"
  ]
}
```

2017-06-27 15:26 UTC, ismail-syed commented
Was able to reproduce the `Warning: The 'await-promise' rule requires type checking` in the VSCode output terminal tab. 

I'm okay with it buried in the console a well. 
But I'm not okay with a pop-up warning on every save. I'm not seeing any of those. @GoodForOneFare have you noticed any of those obnoxious pop-up warnings with this new setup.

2017-06-27 15:47 UTC, lemonmade commented
Based on these discussions, I completely wiped out my changes and got rid of the multiple config stuff entirely. Can you guys take another look?

2017-06-27 17:44 UTC, ismail-syed commented
LGTM 👍 

> What's the benefit of the untyped + full config nowadays?
> In the past, the typed config made VS Code unusable. 

Were there recent changes to VSCode that allowed this work?

2017-06-27 17:46 UTC, ismail-syed commented
Maye this? 
https://code.visualstudio.com/updates/v1_11#_source-control

2017-06-27 17:50 UTC, GoodForOneFare commented
No, not that.  tbh, I can't even remember which editor was problematic.  I was more of an Atom user back then, so you could start by searching through the `linter-tslint` repo for answer.

2017-06-27 18:01 UTC, GoodForOneFare commented
Out of paranoia, I also tested in Sublime.  Displays the same one-time console errors as vscode, and works perfectly.

![connection ts shrink-ray 2017-06-27 13-59-54](https://user-images.githubusercontent.com/673655/27602472-e90fe2c2-5b40-11e7-88a3-57a7bce58c4d.png)

2017-06-27 19:18 UTC, GoodForOneFare approved these changes
LGTM 👍 Tried this out in Atom/VSCode (using shrink-ray, cuz neutron master is busted right now).

(I accidentally approved this in the _sewing-kit next_ PR 😕 )

2017-06-28 12:48 UTC, merged

2017-06-29 17:31 UTC, GoodForOneFare commented
While reviewing the neutron tslint bump, I found [this post](https://github.com/Microsoft/vscode-tslint/issues/70#issuecomment-290744318) about how VS Code used to do _nothing_ when typed rules were present:

> This behavior was changed in TSLint recently (palantir/tslint#2169) so that TSLint now just prints a warning message and continues linting. That should remove one of the big issues mentioned above, so it ought to be possible to just use one tslint.json file now instead of multiple.

So that explains the convoluted nature of `tslint-config-shopify@<3`.